[project]
name = "pykobra"
version = "0.1.0"
description = "ğŸ PyKobra - A CLI tool to generate Flask and FastAPI project structures"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "typer>=0.9.0",
    "python-dotenv>=1.0.0"
]

[project.scripts]
pykobra = "pykobra.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"